server:
  port : 8084

spring:

  kafka:
    bootstrap-servers: 0.0.0.0:29092
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: false
    listener:
      ack-mode: manual

values:
  server-id: 0