#server:
#  port : 8082

spring:

  kafka:
    bootstrap-servers: 192.168.246.101:9092
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: false
    listener:
      ack-mode: manual

values:
  server-id: 0